resources:
- ../../base

namespace: chatbot-dev

namePrefix: dev-
labels:
- pairs:
    environment: development

patches:
- target:
    kind: Deployment
    name: chatbot
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: OLLAMA_URL
        value: "http://192.168.86.27:11434/api/generate"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: OLLAMA_MODEL
        value: "qwen2.5:3b"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: OLLAMA_VISION_MODEL
        value: "moondream"
