resources:
- ../../base

namespace: chatbot-dev

namePrefix: dev-
labels:
- pairs:
    environment: development

patches:
- target:
    kind: Deployment
    name: chatbot
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: chatbot
    spec:
      template:
        spec:
          containers:
          - name: chatbot
            env:
            - name: OLLAMA_URL
              value: "http://192.168.86.27:11434/api/generate"
            - name: OLLAMA_MODEL
              value: "gemma3n:e4b"
            - name: SCRAPER_BASE_URL
              value: "http://dev-webscraper.webscraper-dev.svc.cluster.local"
            - name: UTILITY_BASE_URL
              value: "http://dev-utility-api.utility-dev.svc.cluster.local"
