resources:
- ../../base

namespace: chatbot-dev

namePrefix: dev-
labels:
- pairs:
    environment: development

patches:
- target:
    kind: Deployment
    name: chatbot
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: chatbot
    spec:
      template:
        spec:
          containers:
          - name: chatbot
            env:
            - name: SCRAPER_BASE_URL
              value: "http://dev-webscraper.webscraper-dev.svc.cluster.local:8000"
            - name: UTILITY_BASE_URL
              value: "http://dev-utility-api.utility-dev.svc.cluster.local:8001"
            - name: ORCHESTRATOR_BASE_URL
              value: "http://dev-agent-orchestrator.ai-services.svc.cluster.local:8002"
