apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  labels:
    app: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: chatbot
        image: wmcdonald/chatbot:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: DISCORD_TOKEN
